var songs = [
  "Prelude to Ecstasy",
  "Burn Alive",
  "Caesar on a TV Screen",
  "The Feminine Urge",
  "On Your Side",
  "Beautiful Boy",
  "Gjuha",
  "Sinner",
  "My Lady of Mercy",
  "Portrait of a Dead Girl",
  "Nothing Matters",
  "Mirror",
  "Agnus Dei",
  "Count The Ways",
  "Second Best",
  "This Is The Killer Speaking",
  "Rifle",
  "Woman Is a Tree",
  "I Hold Your Anger",
  "Sail Away",
  "The Scythe",
  "Inferno"
];
